name: Deploy Laravel Tenancy App

on:
  push:
    tags:
      - 'v*' # triggers on tags like v1.0, v1.1, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/your-app-folder

            echo "Fetching latest code..."
            git fetch --all
            git checkout tags/${GITHUB_REF##*/}

            echo "Installing dependencies..."
            composer install --no-dev --prefer-dist --optimize-autoloader

            echo "Running tenant migrations..."
            php artisan tenants:migrate --force

            echo "Setting new version..."
            php artisan tenants:update-version ${GITHUB_REF##*/}
